databases:
  - name: hotel_booking_app
    databaseName: hotel_booking_app_q0kv
    user: hotel_booking_app
    plan: free

services:
  - type: web
    name: hotel_booking_app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hotel_booking_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2